name: Mergeability
on:
  pull_request_review:
    types: [submitted]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - uses: rafaelbastiansch/mergeability-action@1.0.0
      with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
