name: Mergeability
on:
  pull_request_review:
    types: [submitted]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - uses: rafaelbastiansch/mergeability-pr@1.0.2
      with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  afterteste:
    needs: [teste]
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: yarn install
